# Generated by Django 5.1.6 on 2025-02-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='urname',
            new_name='surname',
        ),
    ]
